parameters: {
    CMCscreening: {
        BinaryRelevance: {
            NaiveBayes: {},
            XGBoost: {
                'learning_rate': 0.047359257252671254, 
                'n_estimators': 456, 
                'max_depth': 10, 
                'min_child_weight': 1.0302184732678334, 
                'gamma': 0.4213727720954262, 
                'subsample': 0.8851957635386376, 
                'colsample_bytree': 0.8498304965921355
            }
        },
        ClassifierChain: {

        }, 
        None: {
            CatBoost: {
                'learning_rate': 0.14162336880918014, 
                'max_depth': 10, 
                'l2_leaf_reg': 29.90357616464617
            }
        }
    }
}